services:
  gtfs-cleanup:
    image: alpine:3.21
    container_name: gtfs-cleanup
    restart: unless-stopped
    command: ["sh", "-c", "crond -f -l 8"]
    volumes:
      - ha-config:/data:rw
      - ./scripts/clean.sh:/clean.sh:ro
      - ./crontab.txt:/etc/crontabs/root:ro
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ha-config:
    external: true
    name: services_ha-config
