alias: "Members - Camera Privacy (Away)"
mode: "restart"
triggers:
  - trigger: "state"
    entity_id: "group.members"
    to: "not_home"
    from: "home"
    for: "00:05:00"
actions:
  - action: script.manage_camera_privacy
