alias: "System - Monitor Camera Privacy"
mode: "single"
triggers:
  - trigger: "time_pattern"
    minutes: "/1"
conditions:
  - condition: "template"
    value_template: >
      {{ states('switch.bedroom_privacy_mode') != 'unavailable'
         or states('switch.living_room_privacy_mode') != 'unavailable' }}
actions:
  - action: script.manage_camera_privacy
