#!/usr/bin/env python3
"""Extract Grafana dashboard JSON from k3s-dean-gitops ConfigMaps into monitoring/grafana/dashboards/."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--gitops-dashboards",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "k3s-dean-gitops" / "infra" / "monitoring" / "dashboards",
        help="Directory containing *ConfigMap* YAML files (grafana_dashboard label)",
    )
    parser.add_argument(
        "--out-root",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "monitoring" / "grafana" / "dashboards",
        help="Output root; each Grafana folder becomes a subdirectory",
    )
    args = parser.parse_args()

    if not args.gitops_dashboards.is_dir():
        raise SystemExit(f"Missing gitops dashboards dir: {args.gitops_dashboards}")

    args.out_root.mkdir(parents=True, exist_ok=True)
    written = 0
    folders: set[str] = set()

    for path in sorted(args.gitops_dashboards.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(doc, dict) or doc.get("kind") != "ConfigMap":
            continue
        meta = doc.get("metadata") or {}
        annotations = meta.get("annotations") or {}
        raw_folder = (annotations.get("grafana_folder") or "").strip()
        folder = raw_folder or "_General"
        folders.add(folder)

        data = doc.get("data") or {}
        if not isinstance(data, dict):
            continue

        for filename, content in data.items():
            if not str(filename).endswith(".json"):
                continue
            if not isinstance(content, str):
                continue
            payload = json.loads(content)
            out_dir = args.out_root / folder
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path = out_dir / filename
            out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            written += 1
            print(out_path)

    prov_dir = Path(__file__).resolve().parents[1] / "monitoring" / "grafana" / "provisioning" / "dashboards"
    prov_dir.mkdir(parents=True, exist_ok=True)
    prov_path = prov_dir / "dashboards.yaml"

    lines = [
        "# Generated by scripts/extract-grafana-dashboards-from-gitops.py — do not hand-edit provider list.",
        "apiVersion: 1",
        "providers:",
    ]
    def yaml_double_quoted(s: str) -> str:
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    for folder in sorted(folders):
        if folder == "_General":
            name = "migrated-general"
        else:
            name = "migrated-" + folder.lower().replace(" ", "-").replace("_", "-")
        grafana_folder = "" if folder == "_General" else folder
        lines.append(f"  - name: {name}")
        lines.append("    orgId: 1")
        if grafana_folder:
            lines.append(f"    folder: {yaml_double_quoted(grafana_folder)}")
        else:
            lines.append("    folder: ''")
        lines.append("    type: file")
        lines.append("    disableDeletion: false")
        lines.append("    updateIntervalSeconds: 60")
        lines.append("    allowUiUpdates: true")
        lines.append("    options:")
        container_path = f"/etc/grafana/dashboards/{folder}"
        lines.append(f"      path: {yaml_double_quoted(container_path)}")
        lines.append("")
    prov_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"# Wrote {written} dashboard JSON files, providers -> {prov_path}")

    strip_script = Path(__file__).resolve().parent / "strip-grafana-prometheus-datasource-uid.py"
    subprocess.run([sys.executable, str(strip_script)], check=True)


if __name__ == "__main__":
    main()
