#!/bin/bash
# inject-secrets.sh — Fetch all secrets from BWS and write them to disk.
# Runs at boot (via LaunchDaemon) and can be re-run manually at any time.
# BWS is the single source of truth for all secrets.

set -euo pipefail

COMPOSE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BWS_TOKEN_FILE="/Users/alex/.bws-secret"
BWS_BIN="/usr/local/bin/bws"
BWS_VERSION="2.0.0"
OWNER="alex:staff"

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[inject-secrets]${NC} $*"; logger -t inject-secrets "$*"; }
die()  { echo -e "${RED}[inject-secrets]${NC} $*" >&2; logger -t inject-secrets "ERROR: $*"; exit 1; }

# ── Wait for network ────────────────────────────────────────────────────────

log "Waiting for network..."
for i in $(seq 1 30); do
    if curl -sf --max-time 3 https://api.bitwarden.com/alive >/dev/null 2>&1; then
        break
    fi
    sleep 2
done
curl -sf --max-time 5 https://api.bitwarden.com/alive >/dev/null 2>&1 || die "No network after 60s — cannot reach Bitwarden API"

# ── Ensure bws CLI is installed ─────────────────────────────────────────────

if ! "$BWS_BIN" --version 2>/dev/null | grep -q "$BWS_VERSION"; then
    log "Installing bws CLI v${BWS_VERSION}..."
    TMPDIR=$(mktemp -d)
    curl -fsSL -o "$TMPDIR/bws.zip" \
        "https://github.com/bitwarden/sdk-sm/releases/download/bws-v${BWS_VERSION}/bws-aarch64-apple-darwin-${BWS_VERSION}.zip"
    unzip -o "$TMPDIR/bws.zip" -d /usr/local/bin/
    chmod +x "$BWS_BIN"
    rm -rf "$TMPDIR"
    log "bws CLI installed."
fi

# ── Read BWS access token ──────────────────────────────────────────────────

[[ -f "$BWS_TOKEN_FILE" ]] || die "BWS token file not found: $BWS_TOKEN_FILE"
BWS_ACCESS_TOKEN="$(cat "$BWS_TOKEN_FILE")"
export BWS_ACCESS_TOKEN

ERRORS=0

fetch_secret() {
    local id="$1" dest="$2"
    local val
    val=$("$BWS_BIN" secret get "$id" 2>/dev/null | /opt/homebrew/bin/jq -r .value)
    if [[ -n "$val" ]] && [[ "$val" != "null" ]]; then
        printf '%s' "$val" > "$dest"
        chmod 0600 "$dest"
    else
        log "WARN: failed to fetch secret for $dest (id: $id), keeping existing file"
        ERRORS=$((ERRORS + 1))
    fi
}

# ── Runner secrets → /etc/komodo/runner-secrets/ ────────────────────────────

log "Injecting runner secrets..."
mkdir -p /etc/komodo/runner-secrets
chmod 0700 /etc/komodo/runner-secrets

fetch_secret "2c57558f-d185-4410-ad9d-b385015c9302" /etc/komodo/runner-secrets/github-app-arc-id
fetch_secret "0015f9ab-dd5e-4649-a262-b385015ceac1" /etc/komodo/runner-secrets/github-app-arc-private-key
fetch_secret "c5ad7fae-2f58-4a8b-9651-b413001cad7f" /etc/komodo/runner-secrets/docker-hub-k3s-runner-api-key
fetch_secret "42ea6b6b-3b1e-43d9-8743-b41301665cc9" /etc/komodo/runner-secrets/github-pat-k3s-dean-gitops

cp "$COMPOSE_DIR/runners/entrypoint-wrapper.sh" /etc/komodo/runner-secrets/entrypoint-wrapper.sh
chmod +x /etc/komodo/runner-secrets/entrypoint-wrapper.sh

# ── Runner compose.env (non-secret config) ──────────────────────────────────

log "Writing runner compose.env..."
cat > "$COMPOSE_DIR/runners/compose.env" <<'EOF'
## GitHub Actions Runner Environment
## Generated by inject-secrets.sh — do not edit manually.

## DockerHub
DOCKERHUB_USERNAME=amerenda

## Runner config
RUNNER_SCOPE=repo
RUNNER_WORKDIR=/_work
RANDOM_RUNNER_SUFFIX=false
EOF
chown "$OWNER" "$COMPOSE_DIR/runners/compose.env"

# ── Komodo secrets → komodo/secrets/ ────────────────────────────────────────

log "Injecting Komodo secrets..."
mkdir -p "$COMPOSE_DIR/komodo/secrets"
chmod 0700 "$COMPOSE_DIR/komodo/secrets"

fetch_secret "6a636ea5-2545-45b5-8a0f-b417012a68fd" "$COMPOSE_DIR/komodo/secrets/komodo-dean-db-password"
fetch_secret "239d3146-6227-4e87-a56b-b417012a693c" "$COMPOSE_DIR/komodo/secrets/komodo-dean-passkey"
fetch_secret "13dc9058-7086-40db-8a49-b417012a6978" "$COMPOSE_DIR/komodo/secrets/komodo-dean-webhook-secret"
fetch_secret "f9dec46d-9203-456a-a5d3-b417012a69b5" "$COMPOSE_DIR/komodo/secrets/komodo-dean-jwt-secret"
fetch_secret "44e040b1-20d8-4f7e-bbfa-b417012a69f9" "$COMPOSE_DIR/komodo/secrets/komodo-dean-admin-password"

chown -R "$OWNER" "$COMPOSE_DIR/komodo/secrets"

# ── Komodo compose.env — inject secret values into placeholders ─────────────

log "Injecting Komodo compose.env secrets..."
KOMODO_ENV="$COMPOSE_DIR/komodo/compose.env"

if [[ -f "$KOMODO_ENV" ]]; then
    DB_PASS=$(cat "$COMPOSE_DIR/komodo/secrets/komodo-dean-db-password")
    ADMIN_PASS=$(cat "$COMPOSE_DIR/komodo/secrets/komodo-dean-admin-password")
    PASSKEY=$(cat "$COMPOSE_DIR/komodo/secrets/komodo-dean-passkey")

    # BSD sed: -i '' for in-place without backup
    sed -i '' "s|^KOMODO_DB_PASSWORD=.*|KOMODO_DB_PASSWORD=${DB_PASS}|" "$KOMODO_ENV"
    sed -i '' "s|^KOMODO_INIT_ADMIN_PASSWORD=.*|KOMODO_INIT_ADMIN_PASSWORD=${ADMIN_PASS}|" "$KOMODO_ENV"
    sed -i '' "s|^PERIPHERY_PASSKEYS=.*|PERIPHERY_PASSKEYS=${PASSKEY}|" "$KOMODO_ENV"
    chown "$OWNER" "$KOMODO_ENV"
else
    log "WARN: $KOMODO_ENV not found, skipping"
    ERRORS=$((ERRORS + 1))
fi

# ── Services .env (pihole, bind9) ───────────────────────────────────────────

log "Injecting services secrets..."
PIHOLE_PW=$("$BWS_BIN" secret get "c8157be0-0195-41f3-b3c6-b37100d27645" 2>/dev/null | /opt/homebrew/bin/jq -r .value)
if [[ -n "$PIHOLE_PW" ]] && [[ "$PIHOLE_PW" != "null" ]]; then
    echo "PIHOLE_WEBPASSWORD=$PIHOLE_PW" > "$COMPOSE_DIR/.env"
    chown "$OWNER" "$COMPOSE_DIR/.env"
else
    log "WARN: failed to fetch pihole password"
    ERRORS=$((ERRORS + 1))
fi

mkdir -p "$COMPOSE_DIR/bind9/keys"
BIND_KEY=$("$BWS_BIN" secret get "9904dc3d-6dd4-4727-907e-b3700178ea19" 2>/dev/null | /opt/homebrew/bin/jq -r .value)
if [[ -n "$BIND_KEY" ]] && [[ "$BIND_KEY" != "null" ]]; then
    printf 'key "externaldns-key." { algorithm hmac-sha256; secret "%s"; };\n' "$BIND_KEY" > "$COMPOSE_DIR/bind9/keys/key.conf"
    chown -R "$OWNER" "$COMPOSE_DIR/bind9/keys"
else
    log "WARN: failed to fetch bind9 TSIG key"
    ERRORS=$((ERRORS + 1))
fi

# ── Update Komodo git provider PAT ──────────────────────────────────────────

log "Updating Komodo git provider PAT..."
ADMIN_PASS=$(cat "$COMPOSE_DIR/komodo/secrets/komodo-dean-admin-password" 2>/dev/null)
GITOPS_PAT=$(cat /etc/komodo/runner-secrets/github-pat-k3s-dean-gitops 2>/dev/null)

if [[ -n "$ADMIN_PASS" ]] && [[ -n "$GITOPS_PAT" ]]; then
    # Wait for Komodo to be reachable (may not be up yet at boot)
    KOMODO_UP=false
    for i in $(seq 1 30); do
        if curl -sf http://localhost:9120 >/dev/null 2>&1; then
            KOMODO_UP=true
            break
        fi
        sleep 2
    done

    if "$KOMODO_UP"; then
        JWT=$(curl -sf http://localhost:9120/auth/login/LoginLocalUser \
            -H 'Content-Type: application/json' \
            -d "{\"username\":\"admin\",\"password\":\"${ADMIN_PASS}\"}" \
            | /opt/homebrew/bin/jq -r '.data.jwt')

        if [[ -n "$JWT" ]] && [[ "$JWT" != "null" ]]; then
            PROVIDER_ID=$(curl -sf http://localhost:9120/read/ListGitProviderAccounts \
                -H 'Content-Type: application/json' \
                -H "Authorization: $JWT" \
                -d '{}' | /opt/homebrew/bin/jq -r '.[0]._id["$oid"] // empty')

            if [[ -n "$PROVIDER_ID" ]]; then
                curl -sf http://localhost:9120/write/UpdateGitProviderAccount \
                    -H 'Content-Type: application/json' \
                    -H "Authorization: $JWT" \
                    -d "{\"id\":\"${PROVIDER_ID}\",\"account\":{\"domain\":\"github.com\",\"https\":true,\"username\":\"amerenda\",\"token\":\"${GITOPS_PAT}\"}}" \
                    >/dev/null 2>&1 && log "Komodo git provider PAT updated." \
                    || log "WARN: failed to update Komodo git provider PAT"
            else
                log "No git provider account found in Komodo, skipping PAT update"
            fi
        else
            log "WARN: failed to authenticate with Komodo API"
        fi
    else
        log "Komodo not reachable after 60s, skipping PAT update (will sync on next run)"
    fi
else
    log "WARN: missing admin password or PAT, skipping Komodo PAT update"
fi

# ── Done ────────────────────────────────────────────────────────────────────

if [[ "$ERRORS" -gt 0 ]]; then
    log "Completed with $ERRORS error(s)"
    exit 1
else
    log "All secrets injected successfully."
fi
