apiVersion: 1

datasources:
  - name: Alertmanager
    uid: alertmanager
    orgId: 1
    type: alertmanager
    access: proxy
    url: http://localhost:9093
    isDefault: false
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
