mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883

serial:
  port: tcp://10.100.20.179:6638
  adapter: ember

frontend:
  port: 8099

advanced:
  network_key: [103, 180, 81, 232, 13, 30, 98, 37, 50, 18, 115, 84, 121, 227, 165, 205]
  pan_id: 0xcbf6
  ext_pan_id: [71, 173, 123, 31, 242, 227, 228, 205]
  channel: 15
  homeassistant: true
  last_seen: ISO_8601

availability:
  active:
    timeout: 10
  passive:
    timeout: 1500

device_options:
  retain: true

groups:
  '1':
    friendly_name: living_room
    devices:
      - '0x001788010dcbac08/1'  # fixture
  '2':
    friendly_name: bedroom
    devices:
      - '0x001788010dccdcdb/1'  # Bedroom1
